services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\ExceptionCheckerBundle\Controller\:
        resource: '../../Controller/*'

    c975L\ExceptionCheckerBundle\Form\:
        resource: '../../Form/*'

    c975L\ExceptionCheckerBundle\Security\:
        resource: '../../Security/*'

    c975L\ExceptionCheckerBundle\Service\:
        resource: '../../Service/*'

    c975L\ExceptionCheckerBundle\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
