services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\ExceptionCheckerBundle\Controller\:
        resource: '../../Controller/*'
        bind:
            $roleNeeded: '%c975_l_exception_checker.roleNeeded%'

    c975L\ExceptionCheckerBundle\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
