services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\ExceptionCheckerBundle\Controller\:
        resource: '../src/Controller/*'

    c975L\ExceptionCheckerBundle\Form\:
        resource: '../src/Form/*'

    c975L\ExceptionCheckerBundle\Security\:
        resource: '../src/Security/*'

    c975L\ExceptionCheckerBundle\Service\:
        resource: '../src/Service/*'

    c975L\ExceptionCheckerBundle\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
